/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package metatagorganiser.gui.panels;

import javax.swing.JLabel;
import metatagorganiser.gui.UIController;

/**
 *
 * @author shobana sasi
 */
public class Form1 extends javax.swing.JPanel {

    private UIController controller;
    
    public static final String DEF_LBL_SELECTED_FILES = "Select some files ...";
    public static final String DEF_LBL_TOTAL_FILES = "Total: 0 file(s)";
    /**
     * Creates new form form1
     */
    public Form1(UIController controller) {
        this.controller = controller;
        initComponents();
    }

    public JLabel getLblSelectedFiles() {
        return lblSelectedFiles;
    }

    public void setLblSelectedFiles(JLabel lblSelectedFiles) {
        this.lblSelectedFiles = lblSelectedFiles;
    }

    public JLabel getLblTotalFiles() {
        return lblTotalFiles;
    }

    public void setLblTotalFiles(JLabel lblTotalFiles) {
        this.lblTotalFiles = lblTotalFiles;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectedFiles = new javax.swing.JLabel();
        lblTotalFiles = new javax.swing.JLabel();
        btnSelectFolders = new javax.swing.JButton();
        btnSelectFiles = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        lblSelectedFiles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectedFiles.setText("Select some files ...");

        lblTotalFiles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalFiles.setText("Total: 0 file(s)");

        btnSelectFolders.setText("Select a folder");
        btnSelectFolders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFoldersActionPerformed(evt);
            }
        });

        btnSelectFiles.setText("Select file(s)");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSelectFolders, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(btnSelectFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 147, Short.MAX_VALUE))
                    .addComponent(lblSelectedFiles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalFiles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelectedFiles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalFiles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelectFolders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelectFiles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.onStartButtonClick();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSelectFoldersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFoldersActionPerformed
        controller.onShowFoldersButtonClick();
    }//GEN-LAST:event_btnSelectFoldersActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectFiles;
    private javax.swing.JButton btnSelectFolders;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblSelectedFiles;
    private javax.swing.JLabel lblTotalFiles;
    // End of variables declaration//GEN-END:variables
}
